
import { jsPDF } from 'jspdf';
import { User, MonthlyReportData, Student, StudentPerformance } from '../types';
import { LOGO_URL } from '../constants';

const THEME_COLOR = '#059669'; // Emerald 600
const SECONDARY_COLOR = '#57534e'; // Stone 600
const TABLE_HEADER_BG = '#e7e5e4'; // Stone 200
const ROW_ALT_BG = '#f5f5f4'; // Stone 100

// Helper to load image
export const loadImage = (url: string): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.src = url;
    img.crossOrigin = "Anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => {
        console.warn("PDF Logo load failed");
        resolve(new Image()); 
    };
  });
};

export const PDFService = {
  createDocument: async (title: string, user: User | null): Promise<jsPDF> => {
    const doc = new jsPDF();
    doc.setFillColor(THEME_COLOR);
    doc.rect(0, 0, 210, 24, 'F');
    
    try {
        const img = await loadImage(LOGO_URL);
        if (img.src) {
            doc.addImage(img, 'PNG', 10, 4, 16, 16);
        }
    } catch (e) {
        console.warn("Logo rendering skipped");
    }

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("PRAVAH", 32, 14);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("The Flow of Change", 32, 20);

    doc.setFillColor(255, 255, 255);
    doc.roundedRect(140, 6, 60, 12, 2, 2, 'F');
    doc.setTextColor(THEME_COLOR);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title.toUpperCase(), 170, 13.5, { align: 'center' });

    doc.setFillColor(245, 245, 244); 
    doc.rect(0, 24, 210, 14, 'F');
    doc.setDrawColor(200, 200, 200);
    doc.line(0, 38, 210, 38);
    
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    
    if (user) {
        doc.text(`CENTER: ${user.centerName.toUpperCase()} (${user.centerId})`, 10, 32);
        doc.text(`GENERATED BY: ${user.name}`, 100, 32);
    }
    doc.text(`DATE: ${new Date().toLocaleDateString()}`, 200, 32, { align: 'right' });

    return doc;
  },

  addSectionHeader: (doc: jsPDF, title: string, y: number): number => {
      doc.setFillColor(TABLE_HEADER_BG);
      doc.roundedRect(10, y - 6, 190, 8, 1, 1, 'F');
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(title.toUpperCase(), 15, y - 1);
      return y + 10;
  },

  addField: (doc: jsPDF, label: string, value: string, x: number, y: number, width: number = 90) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(label, x, y);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(String(value), x, y + 5);
  },

  drawTable: (doc: jsPDF, headers: string[], data: string[][], startY: number, customXPositions?: number[]) => {
      let y = startY;
      const rowHeight = 8;
      let xPositions = customXPositions || [10, 35, 95, 155];

      doc.setFillColor(THEME_COLOR);
      doc.rect(10, y, 190, rowHeight, 'F'); 
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      
      headers.forEach((h, i) => {
          doc.text(h, xPositions![i], y + 5.5);
      });
      
      doc.setDrawColor(0, 0, 0); 
      doc.setLineWidth(0.1);
      doc.rect(10, y, 190, rowHeight, 'S'); 
      y += rowHeight;

      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "normal");
      
      data.forEach((row, idx) => {
          if (y > 270) {
              doc.addPage();
              y = 20; 
              doc.setFillColor(THEME_COLOR);
              doc.rect(10, y, 190, rowHeight, 'F');
              doc.setTextColor(255, 255, 255);
              doc.setFont("helvetica", "bold");
              headers.forEach((h, i) => doc.text(h, xPositions![i], y + 5.5));
              y += rowHeight;
              doc.setTextColor(0, 0, 0);
              doc.setFont("helvetica", "normal");
          }
          if (idx % 2 === 0) {
              doc.setFillColor(ROW_ALT_BG);
              doc.rect(10, y, 190, rowHeight, 'F');
          }
          doc.setDrawColor(200, 200, 200);
          doc.rect(10, y, 190, rowHeight, 'S');
          row.forEach((cell, i) => {
              doc.text(String(cell), xPositions![i], y + 5.5);
          });
          y += rowHeight;
      });
      return y;
  },

  generatePerformancePDF: async (student: Student, performance: StudentPerformance, analytics: any, user: User) => {
    const doc = await PDFService.createDocument('Academic Report Card', user);
    let y = 50;

    y = PDFService.addSectionHeader(doc, 'Student Profile', y);
    PDFService.addField(doc, 'Name', student.name, 15, y);
    PDFService.addField(doc, 'Student ID', student.id, 70, y);
    PDFService.addField(doc, 'Class', student.classLevel, 130, y);
    y += 20;

    y = PDFService.addSectionHeader(doc, 'Performance Summary', y);
    PDFService.addField(doc, 'Test Title', performance.testName, 15, y);
    PDFService.addField(doc, 'Average Score', `${Math.round(analytics.average)}%`, 70, y);
    PDFService.addField(doc, 'Strongest Subject', analytics.strongest?.subject || 'N/A', 130, y);
    y += 20;

    y = PDFService.addSectionHeader(doc, 'Detailed Scores', y);
    y += 5;

    const tableData = performance.scores.map(s => [
      s.subject,
      s.score.toString(),
      s.grade,
      s.remarks || '-'
    ]);

    PDFService.drawTable(
      doc, 
      ['Subject', 'Score', 'Grade', 'Remarks'], 
      tableData, 
      y, 
      [15, 75, 105, 135]
    );

    PDFService.addFooter(doc);
    return doc;
  },

  shareFile: async (doc: jsPDF, filename: string) => {
      try {
        const blob = doc.output('blob');
        const file = new File([blob], filename, { type: 'application/pdf' });
        if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({ files: [file], title: 'Share PDF', text: 'Sharing PRAVAH Report' });
        } else {
            doc.save(filename);
        }
      } catch (err) {}
  },

  generateMonthlyReport: async (data: MonthlyReportData, user: User): Promise<jsPDF> => {
      const doc = await PDFService.createDocument('Monthly Attendance', user);
      let y = 50;
      y = PDFService.addSectionHeader(doc, 'Report Overview', y);
      PDFService.addField(doc, 'Month/Year', `${data.month} ${data.year}`, 15, y);
      PDFService.addField(doc, 'Class', data.className, 70, y);
      PDFService.addField(doc, 'Working Days', data.workingDays.toString(), 120, y);
      PDFService.addField(doc, 'Avg Attendance', `${Math.round(data.averageAttendance)}%`, 160, y);
      y += 20;
      y = PDFService.addSectionHeader(doc, 'Student Performance', y);
      y += 5;
      const tableData = data.studentStats.map((s, i) => [
          (i + 1).toString(), s.name, s.studentId, s.presentDays.toString(), `${Math.round(s.percentage)}%`
      ]);
      PDFService.drawTable(doc, ['#', 'Student Name', 'ID', 'Days Present', '%'], tableData, y, [15, 25, 100, 145, 175]);
      PDFService.addFooter(doc);
      return doc;
  },

  addFooter: (doc: jsPDF) => {
    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setDrawColor(THEME_COLOR);
        doc.setLineWidth(0.5);
        doc.line(10, 280, 200, 280);
        doc.setFontSize(8);
        doc.setTextColor(120);
        doc.text(`System Generated Report - PRAVAH App`, 10, 286);
        doc.text(`Page ${i} of ${pageCount}`, 200, 286, { align: 'right' });
    }
  }
};
